### ISSUE TITLE
Make Simulator UUIDs visible to subsequent jobs

### ISSUE THREAD

**Issue by bdellegrazie** [CircleCI-Public/macos-orb#17]
## Describe Request:

When running certain commands against the simulator(s) it's sometimes necessary to ensure they have fully started.
The current semi-documented method is described [on stackoverflow][1]

For this to work, the UUIDs of the simulator(s) need to be visible to subsequent tasks.
According to the [docs][2] this is best achieved by exporting the variable to `BASH_ENV`

The variable name could be parameterised, with a sane default.

The suggestion is to add the UUID of the simulator device(s) to `BASH_ENV` for subsequent ease of use.

## Examples:

```yaml
---
version: 2.1

orbs:
  macos: circleci/macos@2.1.0

jobs:
  ios_tests:
    macos:
      xcode: '13.2.1'
    resource_class: 'medium'
    steps:
      - checkout
      - macos/preboot-simulator:
          device: 'iPhone 11'
          platform: 'iOS'
          version: '15.2'
          device_id_var: 'IPHONE_UUID'    # new parameter
     - run: xcrun simctl bootstatus ${IPHONE_UUID}  # ensures iPhone is fully booted
     - run: some command that requires the simulator fully booted
```

## Supporting Documentation Links:
[1]: https://stackoverflow.com/questions/52438954/mac-simulator-xcode-wait-for-startup-command
[2]: https://circleci.com/docs/2.0/env-vars/#using-parameters-and-bash-environment
